import { test, expect } from '@playwright/test';
test('new sketch: draw, switch, return', async ({ page }) => {
  const logs: string[] = [];
  page.on('pageerror', (e) => logs.push('ERR ' + e.message));
  page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') logs.push(m.type() + ' ' + m.text()); });
  await page.goto('/');
  await page.locator('input[type=file]').first().setInputFiles({ name: 'note.md', mimeType: 'text/markdown', buffer: Buffer.from('# hi') });
  await page.waitForTimeout(500);
  await page.locator('[data-role="rail-new"], button:has-text("New")').first().click();
  await page.waitForTimeout(400);
  await page.getByRole('option', { name: 'Sketch' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  const canvas = page.locator('.sketch-host canvas.interactive');
  await expect(canvas).toBeVisible({ timeout: 20000 });
  await page.locator('.sketch-host [title^="Rectangle"]').first().click();
  const b = (await canvas.boundingBox())!;
  await page.mouse.move(b.x + 200, b.y + 200); await page.mouse.down();
  await page.mouse.move(b.x + 400, b.y + 350, { steps: 5 }); await page.mouse.up();
  await page.locator('.sketch-host [title^="Draw"]').first().click();
  await page.mouse.move(b.x + 100, b.y + 100); await page.mouse.down();
  await page.mouse.move(b.x + 300, b.y + 120, { steps: 8 }); await page.mouse.up();
  await page.waitForTimeout(150);
  await page.locator('[data-role="file-drawer"] button', { hasText: 'note.md' }).first().click();
  await page.waitForTimeout(800);
  await page.locator('[data-role="file-drawer"] button', { hasText: '.excalidraw' }).first().click();
  await expect(page.locator('.sketch-host canvas.interactive')).toBeVisible({ timeout: 20000 });
  await page.waitForTimeout(1000);
  await expect(page.locator('.welcome-screen-center')).toHaveCount(0);
  expect(logs.filter((l) => l.startsWith('ERR'))).toEqual([]);
});
